trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'
    exclude:
      - 'VERSION.txt'
      - 'changelog.md'
      - 'packaging/*'

pr:
  branches:
    include:
      - '*'
    exclude:
      - 'currency/*'
  # paths:
  #   include:
  #     - '*'
  #   exclude:
  #     - 'VERSION.txt'
  #     - 'changelog.md'
  #     - 'packaging/*'


