trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'
    exclude:
      - 'currency/*'

jobs:
  - job: DebugBranchInfo
    displayName: 'Log PR Branch Info'
    steps:
      - script: |
          echo "Source Branch: $(System.PullRequest.SourceBranch)"
          echo "Target Branch: $(System.PullRequest.TargetBranch)"
        displayName: 'Debug Branch Information'
      
  - job: MainJob
    displayName: 'Main Job'
    dependsOn: DebugBranchInfo
    condition: and(succeeded(), not(contains(variables['Build.SourceBranch'], 'refs/heads/currency/'))) 
    steps:
      - script: |
          echo "Running Main Job because the source branch is not excluded."
        displayName: 'Run Main Job'
